#!/bin/bash

# The following method is cross-platform (OS X and Linux)
MYDIR=$(dirname $(python -c 'import os,sys;print os.path.realpath(sys.argv[1])' $0))
cd "$MYDIR"

# Make sure container is running
./up

docker exec 1space /bin/bash -c 'cd /1space; flake8'

export COVER_HTML_DIR=/1space/.coverhtml
docker exec 1space /bin/bash -c "mkdir -p $COVER_HTML_DIR; \
    cd /1space; \
    nosetests --with-coverage --cover-branches \
    --cover-package=s3_sync --cover-erase --cover-html \
    --cover-html-dir=$COVER_HTML_DIR test/unit"
