#!/bin/bash

set -e

# The following method is cross-platform (OS X and Linux)
MYDIR=$(python -c 'import os,sys;print(os.path.dirname(os.path.realpath(sys.argv[1])))' $0)
cd "$MYDIR"

# Make sure container is running
./up

docker exec -e DOCKER=true -e TERM=$TERM \
    -e "COLUMNS=$(tput cols)" -e "LINES=$(tput lines)" \
    -it swift-s3-sync /bin/bash
