#!/bin/bash

# This will be fast if your bouncestorage base image is already up to date in
# your docker image library.
docker pull bouncestorage/swift-aio
# The --build is safe because if nothing in the Dockerfile has changed, it'll
# just quickly "build" entirely from cache and not do anything.
docker-compose up --build -d
docker exec -e DOCKER=true -e TERM=$TERM \
    -e "COLUMNS=$(tput cols)" -e "LINES=$(tput lines)" \
    -it swift-s3-sync /bin/bash
