#!/bin/bash

set -e

# The following method is cross-platform (OS X and Linux)
MYDIR=$(python -c 'import os,sys;print(os.path.dirname(os.path.realpath(sys.argv[1])))' $0)
cd "$MYDIR"

# Make sure container is running
./up

docker exec swift-s3-sync /bin/bash -c \
    'cd /swift-s3-sync; flake8'

export COVER_HTML_DIR=/swift-s3-sync/.coverhtml
docker exec swift-s3-sync /bin/bash -c "mkdir -p $COVER_HTML_DIR; \
    cd /swift-s3-sync; \
    nosetests --with-coverage --cover-branches \
    --cover-package=s3_sync --cover-erase --cover-html \
    --cover-html-dir=$COVER_HTML_DIR test/unit"
