#!/bin/bash

set -e

# The following method is cross-platform (OS X and Linux)
MYDIR=$(dirname $(python -c 'import os,sys;print os.path.realpath(sys.argv[1])' $0))
cd "$MYDIR"

# For full test run, always rebuild & start/stop containers (clean slate)
./scripts/ensure_s3proxy_started
./scripts/rebuild_and_start_main_container

./run_unit_tests
unit_test_status=$?

# Keystone takes a long time to start -- we can kick it off early
./scripts/ensure_keystone_started

echo Waiting for the 1space services to start...
docker exec swift-s3-sync timeout 120 \
    bash -c "until s3cmd -c /swift-s3-sync/s3cfg ls s3://\$CONF_BUCKET/s3-passwd.json; do sleep 1; done"
echo "1space services started"

# cloud-connector will quit if configuration object is not found, so start the
# container only after we created it.
./scripts/ensure_cloud_connector_container_started

docker exec cloud-connector timeout -t 120 \
    bash -c 'until echo > /dev/tcp/localhost/8081; do sleep 1; done'
echo "cloud-connector started"
docker exec 1space-keystone timeout 120 \
    bash -c 'until source openrc && openstack endpoint list|grep swift; do sleep 1; done'
echo "keystone started"

# make sure we can actually authenticate using keystone
docker exec swift-s3-sync timeout 40 \
    bash -c 'until swift --os-auth-url http://1space-keystone:5000/v3 \
             --os-username tester --os-password testing --os-project-name test \
             --os-project-domain-name default --os-user-domain-name default \
             --auth-version 3 --debug stat; do sleep 0.5; done' >/dev/null 2>&1

# the AWS_* environment variables allow some tests to run against real S3
docker exec -e DOCKER=true -e AWS_IDENTITY=$AWS_IDENTITY -e AWS_SECRET=$AWS_SECRET -e AWS_BUCKET=$AWS_BUCKET  swift-s3-sync nosetests /swift-s3-sync/test/integration/
exit $(($unit_test_status + $?))
