#!/bin/bash

set -e

# The following method is cross-platform (OS X and Linux)
MYDIR=$(python -c 'import os,sys;print(os.path.dirname(os.path.realpath(sys.argv[1])))' $0)
cd "$MYDIR"

# Make sure container is running
if test -z "$(docker ps -f name=swift-s3-sync -q)"; then
    ./scripts/rebuild_and_start_main_container
fi
