#!/bin/bash
set -e

# The following method is cross-platform (OS X and Linux)
MYDIR=$(dirname $(python -c 'import os,sys;print os.path.realpath(sys.argv[1])' $0))
cd "$MYDIR"/..

# Build the image
docker pull $(awk 'tolower($1) == "from" && NF == 2{print $2;exit}' containers/keystone/Dockerfile)
docker build --cache-from 1space-keystone -t 1space-keystone -f containers/keystone/Dockerfile .

# Create a network for our party (if necessary)
docker network create --attachable 1space-net 2>/dev/null ||:

docker container stop 1space-keystone 2>/dev/null ||:
docker container rm 1space-keystone 2>/dev/null ||:

docker run -d \
    --network 1space-net --network-alias 1space-keystone \
    --restart on-failure --name 1space-keystone \
    -p "${HOST_KEYSTONE_PORT:-5000}:5000" \
    -p "${HOST_KEYSTONE_AUTH_PORT:-35357}:35357" \
    1space-keystone
