#!/bin/bash
set -e

# The following method is cross-platform (OS X and Linux)
MYDIR=$(dirname $(python -c 'import os,sys;print os.path.realpath(sys.argv[1])' $0))
cd "$MYDIR"/..

# You can set these in "port-mapping.env" to publish the Swift and S3 API
# endpoints to different ports on the host:
# HOST_NAS_CONNECTOR_PORT=...
test -f ./port-mapping.env && . ./port-mapping.env

# Build the image
docker build -t nas-connector -f containers/nas_connector/Dockerfile .

# Create a network for our party (if necessary)
docker network create --attachable swift-s3-sync-net 2>/dev/null ||:

docker container stop nas-connector 2>/dev/null ||:
docker container rm nas-connector 2>/dev/null ||:

docker run -d -v `pwd`:/nas_connector \
    -v /tmp/nasconnector:/srv/nasconnector \
    --network swift-s3-sync-net --network-alias nas-connector \
    --restart on-failure --name nas-connector \
    -p "${HOST_NAS_CONNECTOR_PORT:-8083}:8083" \
    -e AWS_ACCESS_KEY_ID=s3-sync-test -e AWS_SECRET_ACCESS_KEY=s3-sync-test \
    -e NAS_CONNECT_SECRET=mysecret \
    nas-connector
