#!/bin/bash

set -e

# The following method is cross-platform (OS X and Linux)
MYDIR=$(dirname $(python -c 'import os,sys;print os.path.realpath(sys.argv[1])' $0))
cd "$MYDIR"/..

# You can set these in "port-mapping.env" to publish the Swift and S3 API
# endpoints to different ports on the host:
# HOST_S3_PORT=...
# HOST_SWIFT_PORT=...
# HOST_CLOUD_CONNECTOR_PORT=...
test -f ./port-mapping.env && . ./port-mapping.env

# This will be fast if the image is up-to-date and cached:
docker pull bouncestorage/swift-aio:latest

# Build our image
docker build --cache-from 1space:latest -t 1space -f containers/1space/Dockerfile .

# Create a network for our party
docker network create --attachable 1space-net 2>/dev/null ||:

docker container stop 1space 2>/dev/null ||:
docker container rm 1space 2>/dev/null ||:

docker run -d -v `pwd`:/1space \
    --hostname 1space --name 1space \
    --network 1space-net --network-alias 1space \
    -p "${HOST_SWIFT_PORT:-8080}:8080" 1space
